contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #combinegvcfs channel"
    url: https://nfcore.slack.com/channels/combinegvcfs
    about: Discussion about the nf-core/combinegvcfs pipeline
